name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache NPM packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      # Install and build the package
      - name: Install root package
        run: npm install
      - name: Build
        run: npm run build

      # Setup and install the test environment
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install test package
        run: npm install --prefix test
      - name: Cache emulators
        uses: actions/cache@v2.0.0
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}
      - name: Install emulators
        run: test/node_modules/.bin/firebase setup:emulators:firestore 

      # Run tests
      # Upload coverage regardless if test failed or not
      - name: Run tests
        run: npm test
      - name: Codecov
        uses: codecov/codecov-action@v1
        if: ${{ always() }}
        with:
          fail_ci_if_error: true        
      - name: Store coverage report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: coverage
          path: coverage/clover.xml

